# Generated by Django 3.1 on 2020-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость вопроса'),
        ),
    ]
