# Generated by Django 3.1 on 2020-08-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_useranswer_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='cost',
        ),
    ]
